name: Kollektiv
favicon: null
layout_spectrum: 0.5084498475771397
typography_spectrum: 0.8528130939230323
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3280619941651821
  lightness: 0.6717984029091895
  saturation: 0.5903935274109244
  rhythmicContrast: 0.4398113281931728
purpose: []
