typography_spectrum: 0.35425
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.3280619941651821
  lightness: 0.6717984029091895
  saturation: 0.3125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: UA-71540589-1
  facebook: null
  twitter: null
name: Kollektiv
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Produktionen
    id: 3c6b2888-6d2d-44c7-b254-4d66133036f8
    type: content
favicon: null
purpose: []
